version: "3.8"

x-shared-limit:
  &mem_limit
  mem_limit: 512m
  mem_reservation: 128M
  cpus: 0.5

services: 
  db:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_DATABASE: "bookingDB"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "P@$$word"
      MYSQL_ROOT_PASSWORD: "P@$$word"
      ports:
        - 3306:3306
      expose:
        - "3306"
      volumes:
        - my-db:/var/lib/mysql